/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-bright": "#1f2b49",
                "on-error-container": "#ffd2c8",
                "outline": "#6d758c",
                "error-dim": "#d53d18",
                "on-primary-container": "#4a3500",
                "primary-dim": "#ebaf00",
                "tertiary-fixed": "#fff964",
                "surface-variant": "#192540",
                "on-surface-variant": "#a3aac4",
                "secondary-fixed-dim": "#efc92f",
                "primary-container": "#eeb205",
                "on-background": "#dee5ff",
                "surface-container": "#0f1930",
                "inverse-primary": "#7a5a00",
                "on-tertiary-container": "#5c5900",
                "on-tertiary-fixed": "#4e4c00",
                "tertiary-dim": "#f0eb58",
                "surface-container-high": "#141f38",
                "inverse-surface": "#faf8ff",
                "surface-container-lowest": "#000000",
                "surface": "#060e20",
                "on-secondary-fixed-variant": "#675400",
                "primary-fixed-dim": "#ebaf00",
                "tertiary-container": "#f6f05d",
                "surface-dim": "#060e20",
                "on-tertiary": "#656200",
                "on-error": "#450900",
                "surface-tint": "#fdbf1f",
                "on-surface": "#dee5ff",
                "secondary": "#fed73e",
                "tertiary-fixed-dim": "#f0eb58",
                "tertiary": "#fffbd4",
                "on-secondary-fixed": "#463900",
                "on-primary-fixed-variant": "#5f4500",
                "on-secondary": "#5c4b00",
                "outline-variant": "#40485d",
                "background": "#060e20",
                "inverse-on-surface": "#4d556b",
                "on-primary": "#563e00",
                "surface-container-low": "#091328",
                "primary": "#fdbf1f",
                "error-container": "#b92902",
                "on-primary-fixed": "#3b2900",
                "secondary-dim": "#efc92f",
                "surface-container-highest": "#192540",
                "secondary-fixed": "#fed73e",
                "error": "#ff7351",
                "on-tertiary-fixed-variant": "#6c6900",
                "primary-fixed": "#fabd1b",
                "secondary-container": "#715c00",
                "on-secondary-container": "#fff7e8"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans", "sans-serif"],
                "body": ["Plus Jakarta Sans", "sans-serif"],
                "label": ["Plus Jakarta Sans", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px" },
        },
    },
    plugins: [],
}
